### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by peteringram0** [gromo/jquery.scrollbar#83]
This doesn't work at all on firefox (Demo page) Any solutions?

Thanks

**Comment by gromo** [comment]
Mac?

**Comment by peteringram0** [comment]
yer.

**Comment by gromo** [comment]
look at note below in the plugin description here: https://github.com/gromo/jquery.scrollbar

There is known issue that native browser scrollbar cannot be hidden in Firefox on Apple devices, so this plugin is not initialized and you will see native scrollbars.

**Comment by equinox7** [comment]
[nanoScroller](https://github.com/jamesflorentino/nanoScrollerJS) successfully hides native scrollbars in Firefox on Mac OS. So, it is possible.

**Comment by gromo** [comment]
@equinox7 I'm not sure that this way can be used in jQuery Scrollbar

**Comment by equinox7** [comment]
So, the reason mentioned in plugin description is not true:
> There is known issue that native browser scrollbar cannot be hidden in Firefox on Apple devices, so this plugin is not initialized and you will see native scrollbars.

The reason is not in Firefox, it is in your plugin. Am I right?

**Comment by gromo** [comment]
No, you are not right

**Comment by lassn** [comment]
How I fixed it:

there is actually a simple solution for that. You hide the scrollbars by CSS. 
Simply set ".scroll-content" to "width: 200%". Put your scrollable content/text inside another <div> and give that one a width of 50%. The scrollbars of the browser will be in the overflow:hidden area.

```
.scroll-wrapper > .scroll-content {
width: 200%;
}

.scroll-wrapper > .scroll-content .scroll-content-inner {
width:50%;
padding-right: 10px;
}

```
```
<div class="scrollbar-inner">
<div class="scrollbar-content-inner">Hello World</div>
</div>
```

**Comment by equinox7** [comment]
> No, you are not right

It seems, I am right. All these plugins: [perfectScrollbar](https://github.com/noraesae/perfect-scrollbar), [baron](https://github.com/Diokuz/baron), [nanoScroller](https://github.com/jamesflorentino/nanoScrollerJS) work fine in Firefox on Mac OS.

**Comment by gromo** [comment]
It requires one more additional container besides wrapper and I'm trying to avoid this.

**Comment by lininu** [comment]
I tried the latest version of scrollbar and the issue still exists(MacOS Firefox).  So, will it be altered in the future?

**Comment by gromo** [comment]
I'm planning to do this as a hack and only for vertical scrollbar.

**Comment by lininu** [comment]
Don't you consider to make horizonal scrollbar? I use the plugin in the navigation of responsive webpage. When the width become narrowed, the nav can be scroll with pretty style.

**Comment by gromo** [comment]
Unfortunately hiding FF scrollbar on Mac OS is a bit tricky. If it was easy, I would've done it a long time ago.

**Comment by lininu** [comment]
All right, thank you @gromo.

**Comment by fabien** [comment]
@gromo domyou think this fix would help in this case?

https://github.com/Diokuz/baron/commit/aa739717f34a320713b2be0767a55b3e7ce9e724

**Comment by gromo** [comment]
@fabien if you got idea, you can try. I think it should help, but it takes a lot of effort to implement it to current realization

**Comment by Samic8** [comment]
@gromo Hiding the scrollbar in the lasted verision of Firefox seems to be a non-issue anymore. I have created a pull request [here](https://github.com/gromo/jquery.scrollbar/pull/134) to allow Firefox usage.

**Comment by gromo** [comment]
I believe scrollbar type depends on Mac settings, so disabling FF check on Mac is not an option yet. Will check it later.

**Comment by igor-shevchenko** [comment]
@gromo did you have a chance to check it?

**Comment by faudzif** [comment]
I am facing probelm in RTL site firefox and IE shows the scrollbar on left side and in firefox with rtl direction browser.scroll.width shows 0 value in LTR shows 17

**Comment by gromo** [comment]
@faudzif not clear what is the problem. FYI: styles were not updated to support rtl, you have to do it by yourself.
